name: 🐛 Bug Report
description: Report something that isn't working as expected.
title: "[Bug]: "
labels: ["bug"]
assignees:
  - istvank
body:
  - type: markdown
    attributes:
      value: |
        > Please save us some time and use the following template. In 90% of all issues we can't reproduce the problem because we don't know what exactly you are doing.  
        > Just use the following template even if you think the problem is obvious.

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Open console
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: input
    id: browser
    attributes:
      label: Browser
      description: e.g., Chrome 123, Firefox 111, etc.
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Describe the device/environment you're using (e.g., MacBook Pro M2, iPad, Windows 11 laptop).
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or links about the problem here.
    validations:
      required: false
